### ISSUE TITLE
Cant upgrade Statamic to v2.11.13

### ISSUE THREAD

**Issue by axelferdinand** [peda/statamic-glide-vanity-url#3]
![image](https://user-images.githubusercontent.com/10460870/60517028-3ad21f80-9cdf-11e9-8236-e34c7fe38eef.png)

**Comment by peda** [comment]
Hello, 

"permission denied" indicates that a file system permission in your addons folder might be wrong. This can happen when you install an addon manually (with your user) and the web server is running with a different user.
