### ISSUE TITLE
Cant update Statamic

### ISSUE THREAD

**Issue by axelferdinand** [peda/statamic-glide-vanity-url#5]
Get this error when trying to update Statamic:

The command "php composer.phar update peter-rainer/glidevanityurl --prefer-dist --no-dev --optimize-autoloader" failed. Exit Code: 126(Invoked command cannot execute) Output: ================ Error Output: ================ sh: /usr/bin/php: Permission denied

**Comment by peda** [comment]
Same answer as last time (#3) - permission denied in the update process indicates that there is something wrong with your file and folder permissions - you should be able to workaround this by deleting composer.json but doesn't really solve it because your file permissions are still wrong.
